# Generated by Django 4.0 on 2022-06-06 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pversion', models.CharField(default='infinity', max_length=8, unique=True)),
            ],
            options={
                'db_table': 'parent_version',
            },
        ),
        migrations.CreateModel(
            name='Patch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patch_name', models.CharField(max_length=100)),
                ('patch_description', models.CharField(max_length=200, unique=True)),
                ('patch_download', models.CharField(max_length=200, unique=True)),
                ('create_time', models.DateField(auto_now_add=True)),
                ('last_change', models.DateField(auto_now=True)),
                ('patch_remarks', models.CharField(max_length=100, null=True)),
                ('patch_status', models.CharField(choices=[(0, 'discard'), (1, 'normal')], default=1, max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='PatchVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patch_id', models.IntegerField()),
                ('version_id', models.IntegerField()),
            ],
            options={
                'db_table': 'patch_version',
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=5, unique=True)),
            ],
            options={
                'db_table': 'version',
            },
        ),
    ]
