# Generated by Django 4.0 on 2022-06-06 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patch',
            name='patch_description',
            field=models.CharField(max_length=200),
        ),
    ]
