# Generated by Django 4.0 on 2022-06-06 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patch', '0002_alter_patch_patch_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patch',
            name='patch_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
