# Generated by Django 4.0 on 2022-06-02 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userauthority',
            old_name='Authority_id',
            new_name='authority_id',
        ),
        migrations.AlterField(
            model_name='userdata',
            name='user_image',
            field=models.CharField(default='D:\\pycharm\\datatom\\media\\image\\default.png', max_length=200, verbose_name='用户头像'),
        ),
    ]
