# Generated by Django 4.0 on 2022-06-02 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_authority_id_userauthority_authority_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_password',
            field=models.CharField(max_length=100, verbose_name='账号密码——加密过后'),
        ),
    ]
